### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by isMuci** [shaozhiwei1989/Payment#1]
可以写一份readme解释一下各模块之间的作用和相关使用注意事项吗，以及完成进度，功能之类的

**Comment by shaozhiwei1989** [comment]
后续会补充的，目前项目还在完善之中，文档需要等一等。如果有需要 可以邮件沟通 shaozhiwei1989@gmail.com

**Comment by shaozhiwei1989** [comment]
> 可以写一份readme解释一下各模块之间的作用和相关使用注意事项吗，以及完成进度，功能之类的

后续会补充的，目前项目还在完善之中，文档需要等一等。如果有需要 可以邮件沟通 shaozhiwei1989@gmail.com
